services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
    depends_on:
      - kafka
    networks: [msnet]

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
    volumes:
      - ./config-repo:/config-repo:ro
    depends_on:
      - eureka-server
    networks: [ msnet ]

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
    depends_on:
      - eureka-server
      - config-server
    networks: [msnet]

  surveillance-service:
    build: ./surveillance-service
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
      - kafka
      - postgres_surv
    networks: [msnet]
    restart: unless-stopped

  maintenance-service:
    build: ./maintenance-service
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Xms128m -Xmx256m
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    depends_on:
      - eureka-server
      - config-server
      - kafka
      - postgres_maint
      - surveillance-service
    networks: [msnet]
    restart: unless-stopped

# Réseau partagé avec l'infra
networks:
  msnet:
    name: msnet
    driver: bridge
