services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks: [msnet]

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      # IMPORTANT : host de service utilisé à l'intérieur du réseau Docker
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: [msnet]

  postgres_surv:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Bac.2020"
      POSTGRES_DB: surveillance_db
    ports:
      - "5432:5432"
    volumes:
      - pg_surv_data:/var/lib/postgresql/data
    networks: [msnet]

  postgres_maint:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Bac.2020"
      POSTGRES_DB: maintenance_db
    ports:
      - "5433:5432"
    volumes:
      - pg_maint_data:/var/lib/postgresql/data
    networks: [msnet]

volumes:
  pg_surv_data:
  pg_maint_data:

networks:
  msnet:
    name: msnet
    driver: bridge
